# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

from bricks.utils import pandora

pandora.require("grpcio==1.74.0")
import grpc
from bricks.rpc.grpc_ import generic_pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in generic_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GenericStub(object):
    """Generic 定义了一个接受和返回通用 JSON 消息的 RPC 方法。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.rpc = channel.unary_unary(
            '/generic.Generic/rpc',
            request_serializer=generic_pb2.Request.SerializeToString,
            response_deserializer=generic_pb2.Response.FromString,
            _registered_method=True)


class GenericServicer(object):
    """Generic 定义了一个接受和返回通用 JSON 消息的 RPC 方法。
    """

    def rpc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_generic_servicer_to_server(servicer: GenericServicer, server):
    rpc_method_handlers = {
        'rpc': grpc.unary_unary_rpc_method_handler(
            servicer.rpc,
            request_deserializer=generic_pb2.Request.FromString,
            response_serializer=generic_pb2.Response.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler('generic.Generic', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('generic.Generic', rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Generic(object):
    """Generic 定义了一个接受和返回通用 JSON 消息的 RPC 方法。
    """

    @staticmethod
    def rpc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/generic.Generic/rpc',
            generic_pb2.Request.SerializeToString,
            generic_pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
