# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: generic.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from bricks.utils import pandora

pandora.require("grpcio==1.74.0")

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'generic.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgeneric.proto\x12\x07generic\";\n\x07Request\x12\x0e\n\x06method\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\x12\x12\n\nrequest_id\x18\x03 \x01(\t\"K\n\x08Response\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x63ode\x18\x03 \x01(\x05\x12\x12\n\nrequest_id\x18\x04 \x01(\t2;\n\x07Generic\x12\x30\n\x07process\x12\x10.generic.Request\x1a\x11.generic.Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'generic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=26
  _globals['_REQUEST']._serialized_end=85
  _globals['_RESPONSE']._serialized_start=87
  _globals['_RESPONSE']._serialized_end=162
  _globals['_GENERIC']._serialized_start=164
  _globals['_GENERIC']._serialized_end=223
# @@protoc_insertion_point(module_scope)
