"""Bricks 的精简 typed Graph、领域事件与 Runtime API。"""

from .core import AsyncNode, InputPolicy, Node, Output, Ports
from .errors import (
    BricksError,
    BricksRuntimeError,
    EventDispatchError,
    ExecutionCancelledError,
    ExecutionControlError,
    ExecutionError,
    ExecutionTimeoutError,
    GraphError,
    GraphFrozenError,
    GraphValidationError,
    HookExecutionError,
    IncompleteInputsError,
    InvalidOutputError,
    NodeTimeoutError,
    PortValueTypeError,
    RuntimeClosedError,
    StepLimitExceededError,
    UnknownGraphError,
)
from .events import Context, Event
from .execution import Execution, ExecutionLimits, ExecutionStatus
from .graph import Edge, ExecutionPlan, Graph
from .hooks import (
    HookHandle,
    HookPhase,
    HookRegistry,
    HookSignal,
    NodeCall,
    NodeHook,
    ShortCircuit,
    StopGraph,
)
from .observation import (
    CompositeObserverHandle,
    ObservationHub,
    ObserverHandle,
    RuntimeEvent,
    RuntimeEventKind,
    RuntimeObserver,
)
from .policies import InputSelector, PolicyRef, PolicyRegistry
from .plugins import (
    CAP_EVENT_BUS,
    CAP_EVENT_ROUTER,
    CAP_GRAPH_EXECUTOR,
    CAP_GRAPH_WORKER,
    CAP_INPUT_SELECTOR,
    CAP_NODE_HOOK,
    CAP_RUNTIME_OBSERVER,
    CAP_TASK_BACKEND,
    Contribution,
    ExtensionPlugin,
    NodeHookContribution,
    Plugin,
    PluginContext,
    PluginDescriptor,
    PluginHost,
    RegistrationHandle,
)
from .runtime import EventRouter, GraphWorker, LocalRuntimePlugin, Runtime
from .slots import Slot, SlotPool

__all__ = [
    "AsyncNode",
    "BricksError",
    "BricksRuntimeError",
    "Context",
    "Edge",
    "Event",
    "EventDispatchError",
    "EventRouter",
    "Execution",
    "ExecutionCancelledError",
    "ExecutionControlError",
    "ExecutionError",
    "ExecutionLimits",
    "ExecutionPlan",
    "ExecutionStatus",
    "ExecutionTimeoutError",
    "Graph",
    "GraphError",
    "GraphFrozenError",
    "GraphValidationError",
    "GraphWorker",
    "HookExecutionError",
    "HookHandle",
    "HookPhase",
    "HookRegistry",
    "HookSignal",
    "IncompleteInputsError",
    "InputPolicy",
    "InvalidOutputError",
    "Node",
    "NodeCall",
    "NodeHook",
    "NodeTimeoutError",
    "ObservationHub",
    "ObserverHandle",
    "CompositeObserverHandle",
    "Output",
    "PortValueTypeError",
    "Ports",
    "PolicyRef",
    "PolicyRegistry",
    "InputSelector",
    "Plugin",
    "PluginContext",
    "PluginDescriptor",
    "PluginHost",
    "ExtensionPlugin",
    "NodeHookContribution",
    "Contribution",
    "RegistrationHandle",
    "LocalRuntimePlugin",
    "CAP_EVENT_BUS",
    "CAP_TASK_BACKEND",
    "CAP_GRAPH_EXECUTOR",
    "CAP_EVENT_ROUTER",
    "CAP_GRAPH_WORKER",
    "CAP_INPUT_SELECTOR",
    "CAP_NODE_HOOK",
    "CAP_RUNTIME_OBSERVER",
    "Runtime",
    "RuntimeClosedError",
    "RuntimeEvent",
    "RuntimeEventKind",
    "RuntimeObserver",
    "ShortCircuit",
    "Slot",
    "SlotPool",
    "StepLimitExceededError",
    "StopGraph",
    "UnknownGraphError",
]
